### ISSUE TITLE
Clock Bug - Sizing

### ISSUE THREAD

**Issue by RavenLLevitt** [hack-rpi/HackRPI-Mobile2023#26]
Alter sizing so it sclaes to device size, all elements should scale: background, circles, title. Try on at least 3 different sized screens (you can use the web mobile simulator or some other simulator to try multiple devices.) Elements should be properly spaced with padding on either end so they do not go off the sides, use view width to achieve this effect, or if that is not working reply to this issue and we can search for another solution.

<img width="269" alt="image" src="https://github.com/hack-rpi/HackRPI-Mobile/assets/103865865/c838bfb1-7978-48c2-9af0-18e63c9d1de1">

**Comment by RavenLLevitt** [comment]
Secondary: Fix spacing so things are a little tighter, this much space between heading and the clock is not necessary. Also remove the date as this is only for during the event so it's not totally necessary and wastes space. If you have any questions on specifics of spacing reply here or reach out to me on discord.

<img width="267" alt="image" src="https://github.com/hack-rpi/HackRPI-Mobile/assets/103865865/925ac72f-45b6-4e2d-8312-c99523c9b440">

**Comment by Leftykap** [comment]
Fixed by commit https://github.com/hack-rpi/HackRPI-Mobile/commit/54e7fbd7fa2caa8f354158a953bb9b572cf2fe8a, brought closer and also fixed related issues with the spacing being aligned to wrong center of the page, lining up with oversized calendar and also with the different containers holding the 2 rows.
